# Generated by Django 3.2.25 on 2025-08-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20250806_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='applicant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='personalinfo', to='application.application'),
        ),
    ]
