# Generated by Django 3.2.25 on 2025-08-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('application', '0004_personalinfo_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.session'),
        ),
    ]
