# Generated by Django 3.2.25 on 2025-08-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_personalinfo_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='area_of_specialization',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='college',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='programme',
        ),
        migrations.AddField(
            model_name='application',
            name='area_of_specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='programme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
