# Generated by Django 3.2.25 on 2025-08-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('application', '0006_auto_20250806_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='religious_affiliation',
            field=models.CharField(choices=[('christian', 'Christian'), ('islam', 'Islam'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='state_of_origin',
            field=models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('FCT', 'FCT'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='title',
            field=models.CharField(choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.')], max_length=5),
        ),
        migrations.CreateModel(
            name='TranscriptInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(default='The Dean of Postgraduate Studies, Achievers University, Km 1, Idasen-Ute Road, Owo, Ondo State, Nigeria.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_instructions', to='application.application')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.session')),
            ],
            options={
                'verbose_name': 'Transcript Instruction',
                'verbose_name_plural': 'Transcript Instructions',
            },
        ),
        migrations.CreateModel(
            name='EducationalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('diploma_degree', models.CharField(max_length=100)),
                ('from_month', models.CharField(max_length=20)),
                ('from_year', models.CharField(max_length=4)),
                ('to_month', models.CharField(blank=True, max_length=20)),
                ('to_year', models.CharField(blank=True, max_length=4)),
                ('currently_enrolled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_records', to='application.application')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.session')),
            ],
            options={
                'verbose_name': 'Educational Record',
                'verbose_name_plural': 'Educational Records',
            },
        ),
    ]
