# Generated by Django 3.2.25 on 2025-08-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('application', '0007_auto_20250807_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperienceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('employer', models.CharField(max_length=200)),
                ('from_month', models.CharField(max_length=20)),
                ('from_year', models.CharField(max_length=4)),
                ('to_month', models.CharField(blank=True, max_length=20)),
                ('to_year', models.CharField(blank=True, max_length=4)),
                ('current_position', models.BooleanField(default=False)),
                ('responsibilities', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience_records', to='application.application')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.session')),
            ],
            options={
                'verbose_name': 'Work Experience Record',
                'verbose_name_plural': 'Work Experience Records',
            },
        ),
        migrations.CreateModel(
            name='ApplicationWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_no_experience', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='application.application')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.session')),
            ],
        ),
    ]
