# Generated by Django 3.2.25 on 2025-08-07 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_applicationworkexperience_workexperiencerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationworkexperience',
            name='has_no_credentials',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProfessionalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_name', models.CharField(max_length=255)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_number', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='credentials/')),
                ('upload_status', models.CharField(choices=[('idle', 'Idle'), ('uploading', 'Uploading'), ('success', 'Success'), ('error', 'Error')], default='idle', max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='application.application')),
            ],
            options={
                'verbose_name': 'Professional Credential',
                'verbose_name_plural': 'Professional Credentials',
                'ordering': ['-issue_date'],
            },
        ),
    ]
