# Generated by Django 3.2.25 on 2025-08-07 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('application', '0009_auto_20250807_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalcredential',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.session'),
        ),
    ]
