# Generated by Django 3.2.25 on 2025-08-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('application', '0010_professionalcredential_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('child', 'Child'), ('guardian', 'Guardian'), ('grandparent', 'Grandparent'), ('uncle_aunt', 'Uncle/Aunt'), ('cousin', 'Cousin'), ('friend', 'Friend'), ('other', 'Other')], max_length=50)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('work_address', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='application.application')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.session')),
            ],
            options={
                'verbose_name': 'Next of Kin',
                'verbose_name_plural': 'Next of Kin',
                'ordering': ['-id'],
            },
        ),
    ]
