# Generated by Django 3.2.25 on 2025-08-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('application', '0011_nextofkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position_rank', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_undergraduate_teacher', models.BooleanField(default=False)),
                ('relationship_type', models.CharField(choices=[('undergraduate_professor_lecturer', 'Undergraduate Professor/Lecturer'), ('graduate_professor_lecturer', 'Graduate Professor/Lecturer'), ('academic_supervisor', 'Academic Supervisor'), ('department_head', 'Department Head'), ('research_supervisor', 'Research Supervisor'), ('employer_manager', 'Employer/Manager'), ('colleague', 'Colleague'), ('professional_mentor', 'Professional Mentor'), ('other_academic', 'Other Academic'), ('other_professional', 'Other Professional')], max_length=100)),
                ('institution_organization', models.CharField(max_length=200)),
                ('years_known', models.PositiveSmallIntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='application.application')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.session')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'ordering': ['-id'],
            },
        ),
    ]
