# Generated by Django 3.2.25 on 2025-08-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='is_undergraduate_teacher',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='relationship_type',
        ),
        migrations.AddField(
            model_name='reference',
            name='relationship',
            field=models.CharField(default='', max_length=100),
        ),
    ]
