# Generated by Django 3.2.25 on 2025-08-09 02:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('application', '0013_auto_20250809_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField(blank=True, help_text='Additional information relevant to the application (max 2000 characters)', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='application.application')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.session')),
            ],
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or name of the honor/award', max_length=255)),
                ('organization', models.CharField(help_text='Organization or institution granting the award', max_length=255)),
                ('year', models.CharField(help_text='Year received (e.g., 2023)', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', message='Please enter a valid 4-digit year')])),
                ('description', models.TextField(blank=True, help_text='Brief description or criteria (optional)')),
                ('additional_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honors', to='application.additionalinformation')),
            ],
        ),
    ]
