# Generated by Django 3.2.25 on 2025-08-09 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('application', '0014_additionalinformation_honor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required', models.BooleanField(default=False)),
                ('accepted_formats', models.CharField(default='PDF,JPG,PNG', help_text='Comma-separated list of accepted file formats (e.g., PDF,JPG,PNG)', max_length=100)),
                ('max_size_mb', models.PositiveIntegerField(default=5, help_text='Maximum file size in MB')),
                ('max_files', models.PositiveIntegerField(default=1, help_text='Maximum number of files allowed')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='application.application')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.session')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('error', 'Error')], default='completed', max_length=20)),
                ('document_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='application.documentcategory')),
            ],
        ),
    ]
