# Generated by Django 3.2.25 on 2025-08-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_documentcategory_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalcredential',
            name='file',
        ),
        migrations.RemoveField(
            model_name='professionalcredential',
            name='upload_status',
        ),
    ]
