# Generated by Django 3.2.25 on 2025-08-15 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20250811_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalcredential',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='credentials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='professionalcredential',
            name='upload_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('uploading', 'Uploading'), ('success', 'Success'), ('error', 'Error')], default='idle', max_length=20),
        ),
    ]
