# Generated by Django 3.2.25 on 2025-08-15 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20250815_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalcredential',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='professionalcredential',
            name='file',
        ),
        migrations.RemoveField(
            model_name='professionalcredential',
            name='upload_status',
        ),
        migrations.AddField(
            model_name='professionalcredential',
            name='application_work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='application.applicationworkexperience'),
        ),
    ]
