# Generated by Django 3.2.25 on 2025-08-25 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_alter_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
