# Generated by Django 3.2.25 on 2025-08-29 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('application', '0021_alter_reference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='document_category',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='application.application'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.session'),
        ),
    ]
