# Generated by Django 3.2.25 on 2025-08-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_auto_20250829_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(default='text', max_length=255),
        ),
    ]
